#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vim=nvim
alias view=nvim -R
alias ls=exa
alias open=xdg-open

autoload -Uz promptinit
promptinit
prompt fade yellow
#prompt cloud

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#source /usr/local/share/chruby/chruby.sh
#source /usr/local/share/chruby/auto.sh
#chruby ruby-2.6.3

#source $HOME/.zsh_completion/oc_completion.sh

export EDITOR=nvim
export GPG_TTY=`tty`
export GRAALVM=$HOME/graalvm/latest
export GRAALVM_HOME=$GRAALVM
export JAVA_HOME=/usr/lib/jvm/java-11

export PATH=$HOME/bin:$PATH

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/jporter/.sdkman"
[[ -s "/home/jporter/.sdkman/bin/sdkman-init.sh" ]] && source "/home/jporter/.sdkman/bin/sdkman-init.sh"
